service: subject-voting-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline

functions:
  getSubjects:
    handler: handler.getSubjects
    events:
      - httpApi:
          path: /subjects
          method: get
  recordVote:
    handler: handler.recordVote
    events:
      - httpApi:
          path: /vote
          method: post
  options:
    handler: handler.options
    events:
      - httpApi:
          path: /{proxy+}
          method: options

custom:
  serverless-offline:
    httpPort: 3001
    noPrependStageInUrl: true
